version: '3.8'
services:
  db:
    image: postgres:15
    container_name: smartexam_container
    restart: always
    environment:
      POSTGRES_USER: james_admin
      POSTGRES_PASSWORD: Z4mbr4n0
      POSTGRES_DB: smartexam_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: